Homework(exceptions, logger)
Paw3lUlita/LabaHomework2 pull request #4
Opened 2022-12-08 06:16 UTC by Paw3lUlita

2022-12-09 13:42 UTC, vboltrukanis requested changes

2022-12-09 13:42 UTC, vboltrukanis commented on README.md
> +Real Estate Agency structure
Can you plz describe more details on what is this project for, which classes your reviewers should pay special attention, what can user do with your app.

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
> +
remove unnecessary empty lines

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
> +        CentralRepository repository = CentralRepository.getINSTANCE();
getInstance()

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
> +        repository.generateSomeData();
generateRandomData() or generateTestData() -> some data may just confuse a little be, try to be more precise.

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/entity/Complain.java
> +    private Person fromWho;
sender?

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/entity/Complain.java
> +    private Person toWho;
recipient / receiver ?

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/entity/Complain.java
> +    private Person fromWho;
or it can be just from - to

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/entity/House.java
> +        }else {
```suggestion
        } else {
```

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/entity/House.java
>          if(getTenant() != null){
```suggestion
        if(getTenant() != null) {
```

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/entity/Person.java
> +    public Person() {}
add some default values here, maybe we call all clients withount name John Smith, 
so we create a default user as John Smith all the time.

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/exception/OwnerHasNoPropertyException.java
> +public class OwnerHasNoPropertyException extends Exception{
Exceptions should have smth different except for name. Try to make something special about each exception.

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/repository/CentralRepository.java
> +    private static CentralRepository INSTANCE;
You are trying to implement singleton here, and still we use CAPITAL names only for constants, instance in singletons are still lowercased.

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/repository/CentralRepository.java
> +
remove empty line

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/repository/CentralRepository.java
> +    }
empty line between methods

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/repository/CentralRepository.java
> +        data.remove(rentData);
custom exception in case there is no requested data?

2022-12-09 13:42 UTC, vboltrukanis commented on src/main/java/org/example/repository/CentralRepository.java
> +
remove empty lines

2022-12-09 13:56 UTC, vboltrukanis commented on src/main/java/org/example/entity/Agent.java
> +        repository.save(rentData);
maybe rename it to `add()` ?

2022-12-11 11:17 UTC, merged

2022-12-12 22:04 UTC, vboltrukanis commented
You should not merge PR until you get approved status on PR. Once you've finished with fixes, you request for re-review.

2022-12-13 06:53 UTC, Paw3lUlita commented
> You should not merge PR until you get approved status on PR. Once you've finished with fixes, you request for re-review.

OK, sorry, I didn't get it. Now I know.