file service - saving and reading last state of the apllication
Paw3lUlita/LabaHomework2 pull request #6
Opened 2022-12-19 09:56 UTC by Paw3lUlita

2022-12-19 11:56 UTC, vboltrukanis requested changes

2022-12-19 11:56 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
>  }
empty line at the end of file

2022-12-19 11:56 UTC, vboltrukanis commented on src/main/java/org/example/service/InfoFileService.java
> +        this.lastInfoFile = new File("infoData.csv");
why don't you want to set path to file as a param

2022-12-19 11:56 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
> +
this line can be removed

2022-12-19 11:56 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
> +                System.out.println(s);
try to not only print data, but use it for some actions or objects creation

2022-12-20 11:12 UTC, Paw3lUlita commented on src/main/java/org/example/Main.java
> +                System.out.println(s);
Now I store all my rentData in csv file. When new instance of dataRepository is created all data from file is binded to List<rentData>

2022-12-21 16:19 UTC, vboltrukanis requested changes
Add more logs in your project.

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
>  }
fix here

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
> +        repository.writeDataToFile();
this will look better if you can specify file, in which you will wraite your data.
`repository.saveToFile("centralRepository.txt")`

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/entity/Property.java
>      private boolean status; //true = rented, false= to rent
isRented

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/entity/Property.java
>      private boolean status; //true = rented, false= to rent
isAvailable

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/entity/Property.java
> +        return isStatus() == property.isStatus() && Double.compare(property.getRentPrice(), getRentPrice()) == 0 && Objects.equals(getAddress(), property.getAddress()) && Objects.equals(getOwner(), p
you can do like this for better readability:
```
boolean isStatusEqual = (isStatus() == property.isStatus());
boolean isRentPriceEqual = (Double.compare(property.getRentPrice(), getRentPrice()) == 0);
...
return isStatusEqual && isRentPriceEqual && ...;
```
This way it will be possible to edit any condition if needed and add/remove condition easily.

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/entity/Property.java
> +        return isStatus() == property.isStatus() && Double.compare(property.getRentPrice(), getRentPrice()) == 0 && Objects.equals(getAddress(), property.getAddress()) && Objects.equals(getOwner(), p
apply for all equals() method

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/repository/RentDataRepository.java
> +
no need for empty line between variables

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/repository/RentDataRepository.java
> +    private static final String FILE_PATH = "src/main/resources/rentData.csv";
maybe you can move this to some property files, so it might be configured from outside of code itself, but by replacing config file.

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/repository/RentDataRepository.java
> +                FileUtils.write(rentDataFile, rentData.getOwner().getName()+","+
`FileUtils.write(rentDataFile, rentData.toString(), "UTF-8", true)` ??

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/repository/RentDataRepository.java
> +        for(int i = 0 ; i< linesOfFile.size() ; i+=3){
```suggestion
        for(int i = 0; i < linesOfFile.size(); i+=3) {
```

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/repository/RentDataRepository.java
> +        Property house1 = new House("Baker Street 21", null, false, 456.34);
```suggestion
    public void generateTestData() {
        Property house1 = new House("Baker Street 21", null, false, 456.34);
```

2022-12-21 16:19 UTC, vboltrukanis commented on src/main/java/org/example/repository/RentDataRepository.java
> +            throw new NoSuchRentDataFoundException("You trying delete not saved data");
This message can be written inside of `NoSuchRentDataFoundException` itself.
So, when we do  `throw new NoSuchRentDataFoundException();`
in constructor there is smth like 
`super("You trying delete not saved data");`
What we should do here is to specify message, like:
`throw new NoSuchRentDataFoundException(rentData);`
`super(String.format("You trying delete not saved data for tenant: %s",  rentData.getInfo()));`

2022-12-22 19:00 UTC, Paw3lUlita commented
So, I changed all the main method to do proper logic, user can run the program now, see all rent data, rent a house and unrent a house. I know that I need separate repository for Person entities and property entities, but its quite hard to implement it without databases and relations in them

2023-01-11 13:18 UTC, vboltrukanis requested changes
Not all changes were applied, either left a comment or fix.
There is a rule for java files: Add an empty line at the end of file. Use it.
Plz notify me in slack when your ready for re-review. Usually i have too many messages in mail and can sometimes skip message from github.

2023-01-11 13:18 UTC, vboltrukanis commented on src/main/java/org/example/Main.java
> +        while (option != 4);
```
do {
...
} while ( );
```

2023-01-11 13:18 UTC, vboltrukanis commented on src/main/java/org/example/repository/RentDataRepository.java
> +                .findAny().orElseThrow();
```suggestion
        return data.stream()
                .filter(d -> d.getProperty().equals(property))
                .findAny()
                .orElseThrow();
```

2023-01-11 17:16 UTC, Paw3lUlita commented on src/main/java/org/example/Main.java
> +        repository.writeDataToFile();
I,ve got constant FILE_PATH in repo wchich I am using to write data there

2023-01-11 17:18 UTC, Paw3lUlita commented on src/main/java/org/example/entity/Property.java
> +        return isStatus() == property.isStatus() && Double.compare(property.getRentPrice(), getRentPrice()) == 0 && Objects.equals(getAddress(), property.getAddress()) && Objects.equals(getOwner(), p
Done

2023-01-16 11:00 UTC, VbKoshak approved these changes
Take a look at 2 minor comments and the you can merge

2023-01-16 11:00 UTC, VbKoshak commented on src/main/java/org/example/repository/RentDataRepository.java
> +                FileUtils.write(rentDataFile, rentData.getOwner().getName()+","+
Take a look at this comments once again.

2023-01-16 11:00 UTC, VbKoshak commented on src/main/java/org/example/repository/RentDataRepository.java
> +        Property house1 = new House("Baker Street 21", null, false, 456.34);
Take a look at this comment once again.

2023-01-19 19:32 UTC, merged